from enum import Enum


class AgentEventType(str, Enum):
    TALKED = "AGENT_TALKED"
    MOVED = "AGENT_MOVED"
    OBSERVED = "AGENT_OBSERVED"
    WAITED = "AGENT_WAITED"
    EMOTION_CHANGED = "EMOTION_CHANGED"
    RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
